# Generated by Django 3.2.3 on 2021-05-26 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0010_product_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='picture',
        ),
    ]
